services:
  
  opensearch:
    image: opensearchproject/opensearch:latest
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - jaeger
    environment:
      - cluster.name=jaeger-cluster
      - discovery.type=single-node
      - node.name=opensearch
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=av#u-Z7T5W
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: on-failure

  dashboard:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    networks:
      - jaeger
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    ports:
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
    networks:
      - jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=https://opensearch:9200
      - ES_TAGS_AS_FIELDS_ALL=true
      - ES_USERNAME=admin
      - ES_PASSWORD=av#u-Z7T5W
      - ES_TLS_SKIP_HOST_VERIFY=true
    command: [
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--es.tls.enabled=true",
      "--log-level=debug"
    ]
    depends_on:
      - opensearch
    restart: on-failure

  jaeger-query:
    image: jaegertracing/jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=https://opensearch:9200
      - ES_TAGS_AS_FIELDS_ALL=true
      - ES_USERNAME=admin
      - ES_PASSWORD=av#u-Z7T5W
      - ES_TLS_SKIP_HOST_VERIFY=true
      - no_proxy=localhost
    ports:
      - "16685:16685"
      - "16686:16686"
      - "16687:16687"
    networks:
      - jaeger
    command: [
      "--es.num-shards=1",
      "--es.num-replicas=0",
      "--es.tls.enabled=true",
      "--log-level=debug"
    ]
    depends_on:
      - jaeger-collector
    restart: on-failure


  example-hotrod:
    image: jaegertracing/example-hotrod
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    networks:
      - jaeger
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-collector:4318
    depends_on:
      - jaeger-collector
    command: [
      "all",
      "--otel-exporter=otlp",
    ]

volumes:
  esdata:
    driver: local

networks:
  jaeger:
    driver: bridge
